### ISSUE TITLE
kill prossece  ^C is not view correctly

### ISSUE THREAD

**Issue by ayoubelmhamdi** [zdykstra/fuzzypkg#3]
if i stop process , in first time i see this bug in last line 
```bash
$ ./fuzzypkg    
                                               
Executing xbps-install -S 0ad-0.0.24b_2
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
^CPress any key to continue5KB 14%] 26MB/s ETA: 00m00s
```
could you add new line after `Press any key to continue5`

**Comment by zdykstra** [comment]
Thanks for the bug report. This should be fixed in https://github.com/zdykstra/fuzzypkg/commit/78f3d18327148dcfc6d933cc9b2755cbbbc71d05 . I'll tag a new release soon.
