### ISSUE TITLE
Specify border style?

### ISSUE THREAD

**Issue by Barbarossa93** [zdykstra/fuzzypkg#5]
Hi there,

Thanks for sharing this wonderful script! The only thing that I would find as a nice-to-have would be the ability to configure border styles of fuzzypkg. For example, I've changed mine to look like this:

![2022-01-28_04-43-49](https://user-images.githubusercontent.com/57952969/151524393-6b1e7b61-9786-4040-92fb-c00cbc2eb844.png)

Its an easy enough edit, but I've find it also easy to forget to update it/forget how to update it when there are new releases.

**Comment by zdykstra** [comment]
Can you show a diff of the changes you've made? I should be able to support this, I'd just like to see the full scope of what you want changed.

**Comment by Barbarossa93** [comment]
I just changed the values for fzf directly, so I imagine implementing this feature will require a bit more code:
```
73c73
<         --preview-window=down:wrap \
---
>         --preview-window=down:wrap,border-top \
75c75
<         --border=sharp \
---
>         --border=horizontal \
```

**Comment by zdykstra** [comment]
Please try https://github.com/zdykstra/fuzzypkg/tree/border-styling and let me know if that works as expected for you. You'll just need to define the following in your `fuzzypkg.conf` file:

```
BORDER=horizontal
PREVIEW_BORDER=border-top
```

**Comment by Barbarossa93** [comment]
yup, that worked as expected! thanks!
