### ISSUE TITLE
 I am getting a preview error

### ISSUE THREAD

**Issue by voyeg3r** [zdykstra/fuzzypkg#6]
It seems that my xq is returning an error, is it possible to use another app instead of it?

![image](https://user-images.githubusercontent.com/40735/171017676-70cf9ba8-0d87-4225-b6ba-6691860f9675.png)

**Comment by zdykstra** [comment]
Is this something you've written, or is it that just happens to have the name of `xq` but is unrelated to the xtools program? In either case, I've added the configuration option `XQ_BIN` allowing you to override the location of the `xq` binary.
